n3-charts/line-chart

README.md

Also updates the angular version in the example to 1.3.14.
[Plunker link](http://plnkr.co/edit/2hqP1VfrsmrYydezW35G?p=preview)

Update README with working plunker example

---

src/utils/misc.coffee

to handle exception thrown when tooltip mode is chosen to be "NONE" and mouse is hovered over the svg elements.

Update misc.coffee to handle tooltip exception

---

.travis.yml
package.json
test/unit/area_series.mocha.coffee
test/unit/column_series.mocha.coffee
test/unit/legend.mocha.coffee
test/unit/line_series.mocha.coffee
test/unit/second_axis.mocha.coffee
test/unit/thumbnail.mocha.coffee
test/unit/tooltips.mocha.coffee

Hi n3-charts team,
Here is a PR that fixes the unit tests to also work in Chrome.
Best,
Christoph

Fixed unit tests to work with Chrome browser

---

test/unit/utils/BaseFactory.mocha.ts
test/unit/utils/EventManager.mocha.ts
test/unit/utils/FactoryManager.mocha.ts

Added unit tests for EventManager, FactoryManager and BaseFactory

---

src/factories/Axis.ts
src/factories/Container.ts
src/utils/BaseFactory.ts
src/utils/FactoryManager.ts
test/unit/factories/Axis.mocha.ts
test/unit/utils/BaseFactory.mocha.ts
test/unit/utils/FactoryManager.mocha.ts

As we discussed, here the proposed fixes

Fixed tests. Added FactoryManager.registerMany(). FactoryManager.register() now returns instance of factory

---

src/factories/StyleSheet.ts
test/unit/factories/StyleSheet.mocha.ts

Added unit tests for Factory.StyleSheet

---

.ideas.md
examples/tools/index.html.tmpl
examples/tools/test_cases/linear_series/options
src/LineChart.ts
src/factories/Axis.ts
src/factories/Container.ts
src/factories/Transition.ts
src/factories/_index.ts
src/factories/series/Line.ts
src/utils/Dataset.ts
src/utils/Datasets.ts
src/utils/OptionSeries.ts
src/utils/Options.ts
src/utils/_index.ts
test/unit/utils/Datasets.mocha.ts
test/unit/utils/Options.mocha.ts
tsconfig.json

Added basic line drawing

---

index.html

Update d3.js to the recommended cdn

---

README.md
build/line-chart.coffee
build/line-chart.js
build/line-chart.min.js
test/unit/column_series.mocha.coffee

The title says it all. Much needed description of `stacks` in the Readme, as well as tests for the previously implemented fix.

Added stacks description and tests

---

gulpfile.js
src/LineChart.ts
src/factories/Axis.ts
src/factories/Legend.ts
src/factories/Tooltip.ts
src/factories/series/Area.ts
src/factories/series/Column.ts
src/factories/series/Dot.ts
src/factories/series/Line.ts
src/styles/_legend.scss
src/utils/AxisOptions.ts
src/utils/Data.ts
src/utils/EventManager.ts
src/utils/Options.ts
src/utils/Series.ts
src/utils/SeriesFactory.ts
src/utils/_index.ts
test/spec/LineChart.spec.ts
test/spec/factories/series/Area.spec.ts
test/spec/factories/series/Column.spec.ts
test/spec/factories/series/Dot.spec.ts
test/spec/factories/series/Line.spec.ts
test/spec/testUtils.spec.ts
test/spec/utils/Options.spec.ts

here is a PR, that you can see on what I am working on.
I have loads of remarks and comments on testing, but this would fill another hangout session. Maybe we can do this next week, so we can agree on some testing guidelines.
Best.
Christoph

Crazy Refactoring

---

src/LineChart.ts
src/factories/Axis.ts
src/factories/series/Area.ts
src/factories/series/Column.ts
src/factories/series/Dot.ts
src/factories/series/Line.ts
src/utils/AxisOptions.ts
src/utils/Options.ts
src/utils/SeriesOptions.ts
test/spec/utils/Options.spec.ts
test/spec/utils/SeriesOptions.spec.ts

Hi Sébastien,
I am still very active in finding a perfect structure for the Options, so I conitnued refactoring everything. This time I want your opinion before I write all the tests.
Best,
Christoph

Options Refactoring

---

src/LineChart.ts
src/factories/Tooltip.ts
src/styles/_legend.scss
test/e2e/templates/_base.tpl.html
test/e2e/templates/playground.tpl.html

Finally I added the flexible playground as an e2e template. We can use it for loads of tests now.

Added e2e playground and some remarks.

---

src/LineChart.ts
src/app.ts

Using a watcher was SO. FREAKING. PERFORMANCE HEAVY.

Sync between charts now uses $emit and $on

---

docs/usage.md
src/LineChart.ts
src/factories/Axis.ts
src/factories/Container.ts
src/factories/Grid.ts
src/factories/Transition.ts
src/factories/Zoom.ts
src/factories/_index.ts
src/utils/EventManager.ts
src/utils/Options.ts
src/utils/SeriesFactory.ts
test/e2e/templates/pan_zoom.e2e.ts
test/e2e/templates/pan_zoom.hjson
test/e2e/templates/parametric.e2e.ts
test/e2e/templates/parametric.hjson
test/spec/utils/Options.spec.ts

Added pan via an option (see the related e2e test). Next step is to find a cool interface so that the outer world can actually use this ^^.
Also fixed tooltip under Firefox.

Fix and pan

---

docs/getting-started.md
docs/usage.md

Added Getting Started Docs

---

docs/migration.md

Add migration docs

---

index.html
index.js
src/migration.html
src/migration.js

We need to create a new version 2.0.9 before merging this to include docs/migration.md.

Added Migration Guide to gh-pages

---

e2e/templates/legend.e2e.ts
src/factories/Legend.ts
src/styles/_legend.scss

Fixes #420 
http://codepen.io/eranis/pen/mVvJOq

Fixed Bootstrap CSS conflicts

---

.travis.yml

Per https://github.com/travis-ci/travis-ci/issues/5899#issuecomment-209669039

Fixed chrome install in travis

---

docs/usage.md

URL anchor fix

---

.travis.yml
src/factories/Tooltip.ts

As discussed in this thread: https://github.com/n3-charts/line-chart/pull/494 I have switched the tooltip dot from a path to a circle, so that it's radius can be altered via CSS.

Changing the tooltip dot from a path to a circle helps resolve #485

---

docs/usage.md

Hello! I believe your "defined" function in the usage documentation needs to get called with value, otherwise you would get an error that value is undefined.

Make correction to usage documentation
